### ISSUE TITLE
current stable version cannot add new blogs

### ISSUE THREAD

**Issue by bobafetthotmail** [johanneszab/TumblTwo#2]
If I write for example http://blog-name-here.tumblr.com

the current stable version errors out and/or generates an entry with the correct name ( "blog-name-here" ) but wrong download link, ("http://.tumblr.com").

the "previous working release" does not show this issue and it works.

Tested in win10 and win7, all versions apart the "previous working release" error out the same.

Would like to have a working "winxp" version so I can test if It can run in Wine under Linux (which is my main OS).

Btw, the one that works is downloading like a champ, good job. :)

**Comment by johanneszab** [comment]
Hiya. 

I've reuploaded the binaries (stable and XP) which should work now. I haven't noticed the bug because I've actually only tested the clipboard monitor function which automatically adds blogs if it detects a http// .tumblr.com in its content.
Thanks for filling the issue!

Give me some feedback if it works under Linux. Maybe there is someway around because actually I'm mostly using .NET 4.0 stuff which should work under mono I guess. Its also written in WinForms, not WPF.
