### ISSUE TITLE
Tumbltwo not executing

### ISSUE THREAD

**Issue by Linktydraa** [johanneszab/TumblTwo#6]
Hello, I've tried to use Tumbltwo and keep getting an error. I an unable to copy/paste the message, but I took a screen shot that I have linked to. The frustrating part is that I was able to open tumbltwo at first, but after I closed it and tried to open it again, I got this error message. The worst part about the error message is that I can't even close it because it keeps popping up. I have to go into my task manager and end process tree. This seems a bit suspicious.

https://drive.google.com/open?id=0B1M06fow53T-SVRwTTVZeXRlbzA

**Comment by johanneszab** [comment]
I'm not responsible for the website in the background and there is quite an outdated version from last year hosted.

You should also try to use [this version](http://www.jzab.de/files/TumblTwo_old.exe) as it seems you are trying to open either TumblOne or old TumblTwo (version 1.0.6 or below) .tumblr (index) files. That's why the error pops up multiple times as the program wants to read the data files for some blogs but cannot parse them.

The other method would be download the [most recent version](http://www.jzab.de/files/TumblTwo.exe) and simply start from scratch. The downloads itself are quite fast now.

**Comment by Linktydraa** [comment]
Hi,

Thanks for your reply. I tried opening both versions you gave me and pretty much still received the same error. I'm really not computer savvy when it comes to coding things like this, can you tell me what I'm doing wrong? I've uninstalled it and everything and still get this issues. At least it pops up this time, but still doesn't work.
![tumbltwo error again](https://cloud.githubusercontent.com/assets/18748711/14934728/6f3d2bfe-0e6f-11e6-9b18-715e86197e4a.png)

**Comment by Linktydraa** [comment]
It's really frustrating because tumblone is a great program and I really want to use the queuing feature on tumbltwo, but it just doesn't seem to want to work. :(

**Comment by Linktydraa** [comment]
TumblThree seems to be working very well

**Comment by johanneszab** [comment]
Maybe my import is still broken, I cannot really tell from here.

The easiest and quickest solution for you would probably be to start all over again with the [most recent version](http://www.jzab.de/files/TumblTwo.exe), if that's applicable for you.
For this, you either have to remove or move the .tumblr files in the Blogs\Index\ folder, or start the TumblTwo.exe in a different location or set the download location to something else in the Settings window. These files are simply a log book and keep track of already downloaded files, the url and so forth.

You can start with a single blog and see if its really downloading faster for you and then decide if you want to use it or don't want to go all over it again.

**Comment by Linktydraa** [comment]
You are a genius. opening it from a different location is really all it took to gt tumbltwo to work properly. Thank you so much!

**Comment by micheledallatorre** [comment]
I had the same issue: could not crawl or save anything due to a permission problem.

I ended up in this thread and tried to move TumblTwo.exe from my Desktop folder to C:\ folder on Windows.
It worked!

I would suggest to add this on the https://github.com/johanneszab/TumblTwo/blob/master/README.md file.

Cheers and thanks for the good piece of software! :+1:
